# Generated by Django 3.0.4 on 2020-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Time',
            field=models.CharField(choices=[('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-01', '12-01'), ('02-03', '02-03'), ('03-04', '03-04'), ('04-05', '04-05')], max_length=100),
        ),
    ]
