# Generated by Django 3.0.4 on 2020-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200328_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Lecture',
            field=models.CharField(choices=[('CSE310', 'CSE310'), ('INT404', 'INT404'), ('MTH302', 'MTH302')], default='INT404', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Teacher_id',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
